name: Run R Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14-16 * * FRI"
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libxml2-dev \
            libmagick++-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev \
            pandoc \
            git \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            proj-data \
            proj-bin \
            gdal-bin

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/Rlib
          key: ${{ runner.os }}-R-${{ hashFiles('**/scripts/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/Rlib
          echo 'R_LIBS_USER=~/Rlib' >> ~/.Renviron
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ~/.Rprofile

          # Make sure installs + library() calls use your cached library
          Rscript -e '.libPaths("~/Rlib"); install.packages("tidyverse", dependencies = TRUE, lib="~/Rlib")'
          Rscript -e '.libPaths("~/Rlib"); install.packages(c("jsonlite","remotes","magick","usethis","sf","units"), dependencies = TRUE, lib="~/Rlib")'

          Rscript -e '.libPaths("~/Rlib"); remotes::install_github("munichrocker/DatawRappr", lib="~/Rlib", auth_token=Sys.getenv("GITHUB_PAT"))'
          Rscript -e '.libPaths("~/Rlib"); remotes::install_github("hrbrmstr/cdcfluview", lib="~/Rlib", auth_token=Sys.getenv("GITHUB_PAT"))'

          Rscript -e '.libPaths("~/Rlib"); if (!requireNamespace("cdcfluview", quietly=TRUE)) stop("cdcfluview did not install")'

      - name: Run R script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CHART_CODE1: ${{ secrets.CHART_CODE1 }}
          CHART_CODE2: ${{ secrets.CHART_CODE2 }}
        run: |
          . ~/.Renviron
          Rscript "scripts/flu-scraper.R"
